### ISSUE TITLE
Styling TODO's

### ISSUE THREAD

**Issue by KoliosterNikolayIliev** [DimoDimchev/Trivial#308]
FIX Style bugs and other visual effects/defects (Send me all things that needs fixing in slack and I will make TODO list here not to forget something):

- [x]  Dashboard
     - [x] Greeting message should change depending on the time of day
     - [x] Graph gradient
     - [x] Purple borders of navbar buttons
     - [x] Strange glitch when navigating to dashboard (~0.2s)
     - [x] Fix source containers
     - [x] Fix transaction container
- [x]  Portfolio
     - [x] Graph gradient
- [x] Landing page
     - [x] Remove landing page
